### ISSUE TITLE
Support ES6 syntax for Node { Unirest, Native, Request }

### ISSUE THREAD

**Issue by Cazaimi** [postmanlabs/postman-code-generators#115]
**Is your feature request related to a problem? Please describe.**
It is cumbersome to change syntax to make use of ES6 features in each request. 

**Describe the solution you'd like**
Expose a code generator setting for the Node Framework that enables ES6 syntax

**Additional context**
For example: 

```
var request = require('request');
var options = {
  'method': 'GET',
  'url': '{{url}}/hourdata/:id?hour={{hour}}',
  'headers': {
  }
};
request(options, function (error, response) { 
  if (error) throw new Error(error);
  console.log(response.body);
});
```
becomes
```
const request = require('request');
let options = {
  'method': 'GET',
  'url': '{{url}}/hourdata/:id?hour={{hour}}',
  'headers': {
  }
};
request(options, (error, response) => { 
  if (error) throw new Error(error);
  console.log(response.body);
});
```

(This is just an example. I understand that there will be use cases that require a more un-opinionated syntax.)

**Comment by darkCavalier11** [comment]
sure. i want to work on this project and merge it in few days.

**Comment by ajwad-shaikh** [comment]
Hey @Cazaimi, 

This is something I could work upon to get started. I have prior experience in JS and believe that this issue is sufficiently naive for me to start working.

Kindly assign me this issue.

Thanks!
