### ISSUE TITLE
Incorrect handling of single quotes in path

### ISSUE THREAD

**Issue by umeshp7** [postmanlabs/postman-code-generators#132]
**Describe the bug**
Clearly mention the code-generators that are affected by this issue.

Node-js Native, Nodejs-unirest do not resolve url correctly. 

**To Reproduce**

Add a single quote in query params and generate code in "New Code Generation mode" in App.

**Expected code snippet and corresponding request**
If you have a working code snippet that you think solves your problem, please add it here:
Also, add the request.json for which this code snippet was generated.

Single quotes must be escaped.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 
For example you could add the screenshot of the snippet/request builder from Postman app.

<img width="438" alt="Screenshot 2019-11-25 at 12 03 38 PM" src="https://user-images.githubusercontent.com/31915995/69518058-9fd32e00-0f7c-11ea-936e-322398a8fd49.png">

<img width="542" alt="Screenshot 2019-11-25 at 12 04 13 PM" src="https://user-images.githubusercontent.com/31915995/69518067-a792d280-0f7c-11ea-85e1-22e7aff3f0f4.png">

**Additional context**
If you have any reference material which might help us debug the problem please add it here:
Version of postman-code-generators/Postman app:

**Comment by shreys7** [comment]
Also seen in JavaScript - Fetch
