### ISSUE TITLE
Can you please add the support for axios

### ISSUE THREAD

**Issue by irishabh96** [postmanlabs/postman-code-generators#135]

**Comment by Misiu** [comment]
This would be an awesome addition!

**Comment by dilantha111** [comment]
I would like to start on this, if someone hasn't already started on it. Since if axios is added it will be really helpful for me as well.

**Comment by sastava007** [comment]
@dilantha111 I'm already working on this, and about to ship it in 1-2 days.

**Comment by dilantha111** [comment]
awesome buddy !!!!!!! Really waiting for this. It will be really helpful !!!

**Comment by Misiu** [comment]
@dilantha111 looking forward to this. It will be super useful for react developers

**Comment by Misiu** [comment]
@sastava007 any updates? 🙂

**Comment by emanuelet** [comment]
working on this as well. @sastava007 do you have a branch already?

**Comment by sastava007** [comment]
@emanuelet I have worked locally, and haven't pushed my branch. 
Do you still want to continue?

**Comment by emanuelet** [comment]
> @emanuelet I have worked locally, and haven't pushed my branch.
> Do you still want to continue?

yeah, would you like to join forces? I could really use the help

**Comment by sairajsawant** [comment]
Interested to take this up for GSOC 2020. Can @emanuelet help me with the progress done so far?

**Comment by emanuelet** [comment]
On my branch I've basically took the nodejs-request and tweak the code generation to generate a simple axios script. What I'm missing is tweaking the tests for it

**Comment by fjufju** [comment]
I need this also.
I hope one of 4 PR will get merged soon.
Will this be available at postman docs page after PR merge?

**Comment by Misiu** [comment]
axios support got merged, but I don't see it ion postman collection website.
Can it be added there? Where can we ask for it?

**Comment by arlemi** [comment]
Support for generating Axios code snippets in now available in Postman 7.26, update your app or download the latest version from our website. 🙂 

@fjufju @Misiu To get it added to the documentation you can open an issue or directly create a pull request on the `postman-docs` repository here: https://github.com/postmanlabs/postman-docs/
