### ISSUE TITLE
Should `err` variable check or rename as `_`(underscore)

### ISSUE THREAD

**Issue by whthT** [postmanlabs/postman-code-generators#153]
**Describe the bug**
All defined variables must use in GoLang but `err` variable in this line not used.

**Expected code snippet and corresponding request**
We can add nil check on `err` variable.

**Screenshots**
![Adsız](https://user-images.githubusercontent.com/5617385/72806515-65c59600-3c66-11ea-8736-91f7d73b5a19.png)

Related Line: https://github.com/postmanlabs/postman-code-generators/blob/ad1587a9763e94b4c9a98ff7a9276f47cccd324f/codegens/golang/lib/index.js#L284

**Comment by webholik** [comment]
Fixed by #276.
