### ISSUE TITLE
dart support in code generator

### ISSUE THREAD

**Issue by Miamoto-Musashi** [postmanlabs/postman-code-generators#157]
**Additional context**
dart is backbone for many webapps and specially flutter framework which will take the lead in few years, better to be on the train ;)

**Comment by sayoojtmc** [comment]
is anyone working on this?

**Comment by someshkoli** [comment]
Whats the stats for this issue ? I have the dart codegen module ready.

**Comment by akshaydeo** [comment]
Closing this as we are updating #231 regarding this 🙇‍♂
