### ISSUE TITLE
User-Agent header set incorrectly in case of C#

### ISSUE THREAD

**Issue by peterbozso** [postmanlabs/postman-code-generators#158]
**Describe the bug**
Affected code-generator: csharp-restsharp
The problem is clearly described in this issue of RestSharp: https://github.com/restsharp/RestSharp/issues/787
In a nutshell, the code-generator currently sets the User-Agent like this:
```csharp
request.AddHeader("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0");
```
But it's not effective at all, see issue referenced above. The solution is from the same issue as well. The correct way to set it is on the client level, like this:
```csharp
client.UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
```

**To Reproduce**
Generate C# code for a request where the User-Agent header is set, then execute the generated code. Observe that the User-Agent is set to `RestSharp x.x.x.x` instead of the one in the generated code.

**Comment by webholik** [comment]
Fixed by #170.
