### ISSUE TITLE
Adding eslint in system tests 

### ISSUE THREAD

**Issue by umeshp7** [postmanlabs/postman-code-generators#166]
All code-generators have their own eslint check but there are no eslint for `lib`, `test`, `npm` and `index.js`.
Add eslint checks to the root files and folders apart from `codegen` folder.

**Comment by VibhorCodecianGupta** [comment]
@umeshp7 added linting, however there are a lot errors that cause a process exit. Shall I push a commit fixing them as well?

**Comment by shreys7** [comment]
@VibhorCodecianGupta this should be mentioned on the pull request and not on the issue page.😬
