### ISSUE TITLE
Exception handling for index functions

### ISSUE THREAD

**Issue by shreys7** [postmanlabs/postman-code-generators#167]
Add some level of exception handling(try-catch blocks) for functions inside `lib` folder.

**Comment by darkCavalier11** [comment]
i was going through the code base in lib directory i find an import of a file that does not exist.
**postman-code-generators/lib**  
`  languageMap = require('./assets/languages.js');`
there is no languages.js inside asssets. How this works?

**Comment by umeshp7** [comment]
Please run 'node npm/pre-package.js' to get the file languages.js

`language.js` is a file that is not committed to the repository but it is create using the above script. It is required to run the functions `lib` folder and this file is added to the package before the postman-code-generators module is published.

**Comment by sastava007** [comment]
@shreys7 I would love to work on this issue, please assign it to me.
😃

**Comment by kolharsam** [comment]
@shreys7, @umeshp7 what parts exactly require the exception handling? I see that there are 3 methods and the `callback` methods are mostly being passed the error.

Do you wish to replace most of the if statements with try-catch blocks?

**Comment by VibhorCodecianGupta** [comment]
https://www.joyent.com/node-js/production/design/errors
Found this link useful to refer to @shreys7 

Added try catch block in index functions, the link above suggests using error handling methods like throw/catch with synchronous functions for capturing operational errors, which is why I did not replace the callback flow.
Does this issue need adding try/catch to index of separate codegens as well? Will do that if required

**Comment by umeshp7** [comment]
@kolharsam Thanks for the interest. 
You are right most of the places if blocks are handling some of the known errors. And no we don't want to simply replace those with try-catch. 

Identify places where there could be unexpected exceptions. 
For instance: Simply putting contents of the entire getLanguageList function in `try`, and in the `catch` block you could console the error and return an empty array.

**Comment by VibhorCodecianGupta** [comment]
@umeshp7 another attempt at #204

**Comment by sastava007** [comment]
> @umeshp7 another attempt at #204

@VibhorCodecianGupta You should request for a review under your pull request and not here. 😬
