### ISSUE TITLE
Add depcheck

### ISSUE THREAD

**Issue by shreys7** [postmanlabs/postman-code-generators#168]
Depcheck is a tool for analyzing the dependencies in a project to see: how each dependency is used, which dependencies are useless, and which dependencies are missing from package.json and present in code.
Add depcheck integration to this project.
Reference: https://www.npmjs.com/package/depcheck

**Comment by ankit-m** [comment]
@shreys7 can you add a little more description about this?

**Comment by shreys7** [comment]
Dependency check is already present in this repository.
