### ISSUE TITLE
Convert bash scripts(.sh files) to javascript files

### ISSUE THREAD

**Issue by shreys7** [postmanlabs/postman-code-generators#174]
Currently, the following files present inside `npm` folder are bash scripts

- ci-requirements.sh
- package.sh
- test.sh
- zip.sh

Change these bash scripts to javascript files, so that it becomes platform agnostic, i.e. works well on Windows, Linux or macOS. This can be achieved using the node's [shelljs](https://www.npmjs.com/package/shelljs) module.
See `deepinstall.js` file present in `npm` folder for reference.

**Comment by sastava007** [comment]
@shreys7 
I'm working on this.

**Comment by manjots1607** [comment]
@shreys7 
I also want to work on this issue.

**Comment by apshada** [comment]
@sastava007  & @manjots1607  are you still working on this issue, if not then i would like to take this issue

**Comment by sastava007** [comment]
Thanks for your interest, @apshada. 
I have almost completed it, and will push by tonight.

**Comment by debck** [comment]
@shreys7 I would like to work on the issue.

**Comment by PHAGUN-JAIN** [comment]
@shreys7 if this issue is resolved, it should be closed sir!
