### ISSUE TITLE
Curl code from postman doesn't work

### ISSUE THREAD

**Issue by forenheith** [postmanlabs/postman-code-generators#186]
I created request at postman, tested it, all works fine, then I clicked on Code button at the right top corner, copied CURL code, and tried to use it in Windows Shell and got the errors

`At line:2 char:3
+ --header 'x-pr-tenantid: 2720F16E-1E5B-4AA5-93CB-6169E36B5C9E' \
+   ~
Missing expression after unary operator '--'.
At line:2 char:3
+ --header 'x-pr-tenantid: 2720F16E-1E5B-4AA5-93CB-6169E36B5C9E' \
+   ~~~~~~
Unexpected token 'header' in expression or statement.
At line:3 char:3
+ --header 'x-pr-apikey: <<<apikey>>> ...
+   ~
Missing expression after unary operator '--'.
At line:3 char:3
+ --header 'x-pr-apikey: <<<apikey>>> ...
+   ~~~~~~
Unexpected token 'header' in expression or statement.
At line:4 char:3
+ --header 'Authorization: Bearer <<auth>> ...
+   ~
Missing expression after unary operator '--'.
At line:4 char:3
+ --header 'Authorization: Bearer <<auth>> ...
+   ~~~~~~
Unexpected token 'header' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator`

Then I changed --header on -h and got the new ones

`Invoke-WebRequest : A positional parameter cannot be found that accepts argument '--request'.
At line:1 char:1
+ curl --location --request GET 'http://localhost:60513//sip/transactio ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

-h : The term '-h' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:2 char:1
+ -h 'x-pr-tenantid: 2720F16E-1E5B-4AA5-93CB-6169E36B5C9E' \
+ ~~
    + CategoryInfo          : ObjectNotFound: (-h:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

-h : The term '-h' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:3 char:1
+ -h 'x-pr-apikey: <<<apikey>>> ...
+ ~~
    + CategoryInfo          : ObjectNotFound: (-h:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

-h : The term '-h' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:4 char:1
+ -h 'Authorization: Bearer <<auth>> ...
+ ~~
    + CategoryInfo          : ObjectNotFound: (-h:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

**Comment by sastava007** [comment]
@forenheith Let me look into this!

**Comment by umeshp7** [comment]
@forenheith 
Please don't add you API-Key and Auth tokens in an issue. I have removed it from the comment and request you to please rotate all of you API keys and other Authentication tokens. 

Also, we'll need more details about this. Can you please provide us with the following information:

Postman App version:
code generators version (if known):
Code Generators setting in App: 
[Click on the Wrench Icon (Top right) > Settings > General > 'New Code Generation Mode' (Can you tell us if this is switched on or not?)]
If the above setting is OFF, please turn it on and try to generate the cURL code again and let us know if you still face the same issue. 

Finally, can you share the exact Postman Request and the cURL code generated here? (Remove all sensitive information).

**Comment by eugenenekh** [comment]
I guess when you say 'Windows Shell' you mean PowerShell.
If that's true, you need to use another delimiter (backtick - `) instead of \ when you split command into several lines.

Guys, it would be great to have backtick (`) as an option for Line continuation character in addition to \ and ^.
Looks like a super easy to do (:

**Comment by vJRoF** [comment]
I hope i can comment my similar situation within this issue.
If i try to export simple post request with body into cURL and import it back into postman i get new request without any body.

I ended up with such request, for example:
`curl -X POST 'http://example.com/api/v1/orders' -H 'Content-Type: application/json' --data-raw '{
	"entityId":100,
	"count":1
}'`
Postman verison i have is v7.19.1.

**Comment by forenheith** [comment]
`curl --location --request POST 'https://myapi.com/books/status' `
--header 'Content-Type: application/xml' `
--header 'x-eome-tenantid: 00000000-0000-0000-0000-000000000000' `
--header 'x-some-apikey: fseim2angST58QnVjDs7cKgaxX474bwTnqKnD7tZY8eLEWx429Ga6P96cteCjVpgFmhF7juPjB5' `
--header 'Content-Type: application/xml' `
--data-raw '<?xml version="1.0" encoding="utf-8"?>
<e-ML>
	<Status>
		<station_id>1370</station_id>
		<book_status>Ready</h35_status>
		<last_updated>2015 09 17 T05:14:40</last_updated>
	</Status>
</e-ML>'`
