### ISSUE TITLE
NodeJs - Request now depreciated?

### ISSUE THREAD

**Issue by Furry** [postmanlabs/postman-code-generators#188]
Perhaps replacing the "NodeJS - Request" Code Snippet with Node-Fetch or Axios? If this is something that's okay to do, I can see about making a pr for it.

**Comment by umeshp7** [comment]
@Furry 
We are not looking to remove NodeJS Request just yet. And we have a code-generator for js-fetch. You can track the progress on Axios here: https://github.com/postmanlabs/postman-code-generators/issues/135

**Comment by Furry** [comment]
Ah alright, good to know!
