### ISSUE TITLE
Dependency Management by maven

### ISSUE THREAD

**Issue by nikhilmuz** [postmanlabs/postman-code-generators#189]
**Is your feature request related to a problem? Please describe.**
Dependency management should be robust. Inspired by PR #187. 

**Describe the solution you'd like**
Something like maven should be used for dependency management rather than hardcoding library itself or varying links for the library. Refer [Maven](http://maven.apache.org/)

**Additional context**
Currently, we are hardcoding binaries and jar in a zip for managing dependency for java codegens like okhttp etc which is difficult to manage and bumping version is not that easy and for single dependency change, entire zip is committed causing larger commit size as zip file is committed as a whole in binary, not on line basis. Same is for updating dependencies.

**Comment by umeshp7** [comment]
@nikhilmuz Feel free to create a PR for this if you'd like. We would be happy to review.

**Comment by nikhilmuz** [comment]
I would love to. I will submit the PR after resolving the existing one.

**Comment by umeshp7** [comment]
Feel free to reopen this when you have created a PR.
