### ISSUE TITLE
Add support to Axios

### ISSUE THREAD

**Issue by byeze** [postmanlabs/postman-code-generators#241]
**Is your feature request related to a problem? Please describe.**
I generally use Axios for my API calls, and so when I try to generate code on Postman, it only has Native, Request and Unirest. I would love to have Axios.

**Describe the solution you'd like**
I would like to have code generated for Axios, a promise based library.

**Additional context**
-

**Comment by sastava007** [comment]
@byeze We appreciate you for coming forward and sharing us what exactly our users want. 
It's already been marked as a feature request #135  and the Postman team is working on it. 
We'll try to deliver it as quick as possible.

**Comment by byeze** [comment]
Thank you!
