### ISSUE TITLE
cURL snippets fail on Windows due to Single Quote

### ISSUE THREAD

**Issue by mzhukovs** [postmanlabs/postman-code-generators#248]
**Describe the bug**
@umeshp7 @shreys7 
#72 #92 
this causes a problem on Windows machines; by pasting the cURL generated code snipped into a Windows Command Prompt, you get the misleading error message:

> curl: (1) Protocol "'https" not supported or disabled in libcurl

Which is just due to the single quotes, and can be fixed only by using double quotes.

see here: https://stackoverflow.com/questions/6884669/curl-1-protocol-https-not-supported-or-disabled-in-libcurl

Much like you have the option to change the line continuation character from \ to ^ in the Settings there, I think the single vs. double quote should also be an option.

As a bonus, would be nice if Postman detected that the machine is Windows and defaulted to ^ and " in the settings accordingly.

**To Reproduce**
Paste any resulting cURL snippet into a win cmd prompt

**Comment by someshkoli** [comment]
@umeshp7  the line breaker option is available in the `options` but i guess is not set in the postmanapp. 
![image](https://user-images.githubusercontent.com/41543649/82157942-3cc6b200-98a2-11ea-942e-6a23678ee172.png)

**Comment by JanOonk** [comment]
This still causes trouble:
curl -L -X POST "https://localhost:5443/connect/token" -H 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'client_id=m2m.client' --data-urlencode 'scope=weatherapi.read' --data-urlencode 'client_secret=SuperSecretPassword' --data-urlencode 'grant_type=client_credentials'

should be

curl -L -XPOST "https://localhost:5443/connect/token" -H "Content-Type: application/x-www-form-urlencoded" --data-urlencode "client_id=m2m.client&scope=weatherapi.read&client_secret=SuperSecretPassword&grant_type=client_credentials"

Notice the removal of the space between -X and POST! Also the data needs double quotes.

My settings were:
![image](https://user-images.githubusercontent.com/13236774/103476571-66900300-4db7-11eb-99ab-84d4a4624c06.png)
![image](https://user-images.githubusercontent.com/13236774/103476577-727bc500-4db7-11eb-88e7-69569cf2a667.png)
![image](https://user-images.githubusercontent.com/13236774/103476581-7871a600-4db7-11eb-9efc-e42c946d4741.png)
