### ISSUE TITLE
Add PHP Guzzle code generator

### ISSUE THREAD

**Issue by jasny** [postmanlabs/postman-code-generators#283]
**Is your feature request related to a problem? Please describe.**
Code generation for PHP is only available for low-level functions directly (like Curl), or outdated libraries (like HTTP_Request2).

**Describe the solution you'd like**
Implement a code generator for [Guzzle](https://packagist.org/packages/guzzlehttp/guzzle) and/or a generic [PSR-18](https://www.php-fig.org/psr/psr-18/) generator.

**Comment by taddev** [comment]
I'd like to see this also. I think I'll try to work up a solution.

**Comment by mubassirhayat** [comment]
Is there a timeline on when we'll be able to see this?? Is there a way the community can contribute??

**Comment by andrewgosselin-nt** [comment]
I would also love to see this feature added, I've always thought postman was missing guzzle in the code generators.

**Comment by manobalansm** [comment]
it's ease our time, to convert entire collection to php api's. instantly, 
so make it.

**Comment by manobalas** [comment]
it's ease our time, to convert entire collection to php api's. instantly,
so make it.

**Comment by insign** [comment]
I couldn't found any PR for Guzzle, but anyway, open PR looks like giving flies....

**Comment by EnGlamdring** [comment]
We'd love to see this too. Any news?

**Comment by Hamulus** [comment]
I would like to see this feature too

**Comment by jacarvajal** [comment]
Subscribed, I think this is a great idea, Guzzle is widely used in PHP projects.
