### ISSUE TITLE
cURL globbing error for brackets

### ISSUE THREAD

**Issue by tconrado** [postmanlabs/postman-code-generators#305]
### Decription
cURL will fail if in the URL there are nested brackets "{" or "}" as it was not escape neither the -g option set
eg. https://my.restdb.io/rest/users?q={"orderInfo":{"$elemMatch":{"userID":3366129827943}}}
 
### To Reproduce

1. Create a get request
2. Use any http that has "{" and "}"  
`https://my.restdb.io/rest/users?q={"orderInfo":{"$elemMatch":{"userID":3366129827943}}}`
3. Copy the code for cURL
`curl -X GET 'https://my.restdb.io/rest/users?q={%22orderInfo%22:{%22$elemMatch%22:{%22userID%22:3366129827943}}}' -H 'apikey: 5bd08e5ac19ba11113b50dad' -H 'x-apikey: 5bd08e5ac19ba11113b50dad'`
4. Run on Bash
5. Get the error 
_curl: (3) [globbing] nested brace in column 52_

### To fix

**Detect nested braces in the URL and add the option "-g" to cURL or escape braces as "\{"**

`curl -g -X GET 'https://my.restdb.io/rest/users?q={%22orderInfo%22:{%22$elemMatch%22:{%22userID%22:3366129827943}}}' -H 'apikey: 5bd08e5ac19ba11113b50dad' -H 'x-apikey: 5bd08e5ac19ba11113b50dad'`

or 

`curl -X GET 'https://my.restdb.io/rest/users?q={%22orderInfo%22:\{%22$elemMatch%22:\{%22userID%22:3366129827943\}\}}' -H 'apikey: 5bd08e5ac19ba11113b50dad' -H 'x-apikey: 5bd08e5ac19ba11113b50dad'`

**Comment by someshkoli** [comment]
Possible duplicate  #253
PR: #258 
Also curl breaks only when there are nested {{}} or [[]]

**Comment by umeshp7** [comment]
duplicates #253
