### ISSUE TITLE
HTTP code generation doesn't handle variables in URL correctly

### ISSUE THREAD

**Issue by andrewhickman** [postmanlabs/postman-code-generators#315]
**Describe the bug**

The HTTP code generator, when given a URL starting with a variable like `{{my_base_url}}/path`, generates code like
```
GET /path HTTP/1.1
Host: https://example.com/base
```
Note the host header incorrectly includes both the scheme and part of the path, while the actual path is incomplete

Expanding the variable in manually causes the generator to give the correct output
```
GET /base/path HTTP/1.1
Host: example.com
```

**To Reproduce**

- Set the `my_base_url` variable to `https://example.com/base`
- Create a GET request with the url set to `{{my_base_url}}/path`
- View the generated HTTP code

**Screenshots**

For example you could add the screenshot of the snippet/request builder from Postman app.
![image](https://user-images.githubusercontent.com/19718247/89634221-f11e1600-d89c-11ea-8172-5fab46d525e5.png)

**Comment by VallariAg** [comment]
I'll like to work on this! Could you please assign it to me?

**Comment by VallariAg** [comment]
On the application, I noticed this is a general issue and not just with `http` codegen.
Here is the options in  `NodeJs - Native` snippet:
```
var options = {
  'method': 'GET',
  'hostname': 'https://example.com/base',
  'path': '/path',
  'headers': {
    'Content-Type': 'application/json'
  },
  'maxRedirects': 20
};
```
The `convert` function takes in a `request` parameter which is a `PostmanRequest` object made by postman-collection. 
I think the issue lies somewhere in postman-collection's `Request` function and how it handles a string URL.

If this sounds right, should I open an issue on the postman-collection repo?

**Comment by umeshp7** [comment]
@VallariAg Yes seems like it, I observed the same behavior. Able to reproduce this in `Python - http.client`, `NodeJs - native` and `HTTP`. 
When exported the collection found this in that request: 
```
"url": {
   "raw": "{{url}}/check",
       "host": [
	     "{{url}}"
	],
	"path": [
		"check"
	]
}
```
@codenirvana Thoughts?

**Comment by codenirvana** [comment]
@umeshp7 If your use case requires replacing variables in a parsed URL object, always:
Convert it back to a string -> replace variables -> parse again.

**Comment by umeshp7** [comment]
@codenirvana The logic for replacing the variables isn't in code-generators, we use the information directly provided to us in the sdk's url object. https://github.com/postmanlabs/postman-code-generators/blob/develop/codegens/http/lib/util.js#L170

**Comment by webholik** [comment]
@codenirvana We are getting wrong url from Runtime when the URL starts with a variable. 
For example if you have a variable, say `path = https://example.com/path` and you use it in the address:
![Screenshot_20201023_132200](https://user-images.githubusercontent.com/360759/96971542-e5083300-1532-11eb-8754-7a276d058b0a.png)

This is the url object that is passed to the code-generator:
```
"url": {
    "path": [
      "hello"
    ],
    "host": [
      "https://example.com/path"
    ],
    "query": [],
    "variable": []
  }
```

As you can see it is taking the value of the variable as Host and the rest as path.

**Comment by codenirvana** [comment]
@umeshp7 @webholik If you are resolving variables in a URL (not sure how it's done in code-gen) you have to parse it again.
That's how it's done in [postman-runtime](https://github.com/postmanlabs/postman-runtime/blob/develop/lib/runner/extensions/request.command.js#L49) also.

So, if the input source is not guaranteed to provide a proper parsed URL, I suggest always parsing it again in the code generator.
