### ISSUE TITLE
Code output for PowerShell producing errors

### ISSUE THREAD

**Issue by dpwilliamson** [postmanlabs/postman-code-generators#318]
Describe the bug
I created an API in Postman and it functions within Postman as expected. I then take the code generator and generate the code for PowerShell - RestMethod. I then am going into PowerShell to execute the script, and I get an error for invalid paths and an invalid request on the expected type of Multipart Form Request. I have contacted the software development team for Zoho where I am attempting to post to, and they said it's an issue with the Postman code generator and to contact Postman. Please assist me with this. Thank you!

To Reproduce
Created API in Postman.  It works as expected in Postman, but when I use the code generator, it doesn't work for this collection.  I have gotten it to work in other collections with some slight tweaks, but this one will not.  It's holding up a major project for a software implementation at my work.

It will not allow me to attach my collection to this request.  Please email me for me to submit a copy of my collection to demonstrate my issue, or let's do a screen share session.  Thank you!

Dan Williamson

**Comment by umeshp7** [comment]
@dpwilliamson Could you send us the collection at help@postman.com ? 
Is there any specific error you are facing while running the Powershell code snippet? 

Also please share some details around App - like app version, OS etc.

**Comment by dpwilliamson** [comment]
Has this been resolved?  I’ve spent hours compiling the information to send you everything you’ve asked me for, including videos, and I have not heard back.  Thanks,
Dan

**Comment by akshaydeo** [comment]
@dpwilliamson really sorry for this. We are looking into this on priority 🙇‍♂. I will keep this ticket updated as we ship a fix.

**Comment by dhwaneetbhatt** [comment]
@dpwilliamson The PowerShell output generated by Postman is compatible with PowerShell versions 6 and above, based on .Net Core. I tried running a similar code snippet in PowerShell 7.3.2 on Windows 11, there was a minor issue of the file path being incorrect (it had an extra forward slash in the file path), but once I corrected that manually, it worked fine.

We will keep this issue open and try to fix the file path issue so the generated code can run in PowerShell without any modifications. We will also look into the feasibility of supporting Windows PowerShell.

#### References
- [Installing PowerShell on Windows](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.3)
- [Differences between PowerShell 6+ and Windows PowerShell 5.1](https://learn.microsoft.com/en-us/powershell/scripting/whats-new/differences-from-windows-powershell?view=powershell-7.3)

**Comment by aman-v-singh** [comment]
Closing the issue as it is fixed.
