### ISSUE TITLE
Bad Python - Requests code snippet

### ISSUE THREAD

**Issue by MicaelJarniac** [postmanlabs/postman-code-generators#326]
**Describe the bug**
The **Python - Requests** code snippet generated for a request has inconsistent style.

```python
import requests

url = "..."

payload = {}
headers= {}

response = requests.request("GET", url, headers=headers, data = payload)

print(response.text.encode('utf8'))

```

**To Reproduce**
1. Go to the Postman app
1. Click on a request
1. Click on **Code**
1. Search for **Python - Requests**
1. Select it
1. See the Python code snippet

**Expected code snippet and corresponding request**
The Python code snippet should have a consistent style, preferably following a well established convention like [PEP 8](https://www.python.org/dev/peps/pep-0008/).

```python
import requests

url = "..."

payload = {}
headers = {}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text.encode("utf8"))

```

**Screenshots**
![Screenshot](https://i.imgur.com/LVEl4Hw.png)

**Additional context**
Version of postman-code-generators/Postman app:
Postman for Windows
Version 7.31.1
win32 10.0.18363 / x64

https://www.python.org/dev/peps/pep-0008/#other-recommendations

**Comment by webholik** [comment]
Fixed by #316 and #292.
