### ISSUE TITLE
curl data-raw - incorrect parameter

### ISSUE THREAD

**Issue by fusionneur** [postmanlabs/postman-code-generators#327]
**Describe the bug**
generated curl includes --data-raw which is not recognized on linux

**Comment by webholik** [comment]
`--data-raw` has been recognised as far back as version `7.47`, which we test for,  and I confirmed it is present in `7.68`. Which version were you using?

**Comment by umeshp7** [comment]
@fusionneur Hey, can you check which version of curl you are using? As mentioned by @webholik I can see that it was added in `7.43.0`. 
Here is the cURL man page https://curl.se/docs/manpage.html 
```
--data-raw <data>
(HTTP) This posts data similarly to -d, --data but without the special interpretation of the @ character.
See also -d, --data. Added in 7.43.0. 
```
Let us know if there is any other issue with the generated code. Closing it for now. Feel free to reopen

**Comment by GerryLon** [comment]
short option for curl: "--data-raw" shoule be "-d"
