### ISSUE TITLE
Nodejs - generate  GraphQL  request incorrect multi line query

### ISSUE THREAD

**Issue by HuyNVuong** [postmanlabs/postman-code-generators#337]
**Describe the bug**
On any Nodejs request, GraphQL request is not generating the correct query

**To Reproduce**
 1. Go to the Postman app
 2. Select or generate a graphQL request that has this following template 
```
query {
  object {
    field
    field
  }
}
```
 3. Click on Code
 4. Search for any Nodejs - Requests
 5. Select it
 6. See the generated Nodejs  code snippet

**Expected code snippet and corresponding request**
GraphQL request should be able to support multi-line query

**Screenshots**

![image](https://user-images.githubusercontent.com/35347897/92765589-1a7a0800-f35b-11ea-9c1f-290bf45c9299.png)

**Additional context**
A quick fix for this would be adding multi-line character instead of quote character on sanitize body request

**Comment by karmanya007** [comment]
@HuyNVuong Isn't this the correct code?

![gQL_nodejs](https://user-images.githubusercontent.com/24437967/97081068-a13e2800-161d-11eb-92dc-c8db2bf2066f.jpg)

For this request

![gQL_nodejs_req](https://user-images.githubusercontent.com/24437967/97081090-c2067d80-161d-11eb-9b2b-b300f92c7cd2.jpg)

**Comment by HuyNVuong** [comment]
That is correct, but the code would not compile if run locally?

**Comment by HuyNVuong** [comment]
This issue is resolved at #339
