### ISSUE TITLE
Add R to Generate Code Snippets

### ISSUE THREAD

**Issue by pmlove3** [postmanlabs/postman-code-generators#347]
Hi, Please can you add an R code snippet in the Generate Code Snippets section. Thank you for your help.

**Comment by GeniusCoders** [comment]
Yeah this is much needed!!

**Comment by ad0861** [comment]
The specific R libraries this should be implemented for are httr and curl.

**Comment by soobbea** [comment]
+1 

The auto-generated R SDK by [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) seems pretty heavy so I would prefer code snippets using curl instead

**Comment by nviraj** [comment]
Would really love this to be honest! 
I encounter a lot of Postman collections in the wild but translating them manually to httr/ curl in R is a bit painful. 
This would be a really beneficial addition to the Postman ecosystem considering R is at rank 12 according to TIOBE index.

**Comment by umeshp7** [comment]
Thanks for feedback and this feature request. I am happy to let you know that we will be soon adding support for this. 

@ad0861 @nviraj @soobbea Please let us know your preference on httr vs rcurl. We have started working on both. And it would be great to know which ones are more commonly used in the industry. 

cc @LuisTejedaS @erfemega

**Comment by ad0861** [comment]
> Thanks for the feedback and this feature request. I am happy to let you know that we will be soon adding support for this.
> 
> @ad0861 @nviraj @soobbea Please let us know your preference on httr vs rcurl. We have started working on both. And it would be great to know which one is more popular or commonly used in the industry.
> 
> cc @LuisTejedaS @erfemega

I would recommend httr as it's very popular. The maintainers of the R library are also very active in the R community.

**Comment by nviraj** [comment]
> Thanks for the feedback and this feature request. I am happy to let you know that we will be soon adding support for this.
> 
> @ad0861 @nviraj @soobbea Please let us know your preference on httr vs rcurl. We have started working on both. And it would be great to know which one is more popular or commonly used in the industry.
> 
> cc @LuisTejedaS @erfemega

Thanks for taking this up @umeshp7! From my personal experience and working with other colleagues, httr seems to be more prevalent. In case it is useful, I am attaching stats for number of installs from RStudio's CRAN mirror (Not comprehensive as it is just a mirror but might indicate trends)
httr - [![](https://cranlogs.r-pkg.org/badges/httr)](https://cran.r-project.org/package=httr)
RCurl - [![](https://cranlogs.r-pkg.org/badges/RCurl)](https://cran.r-project.org/package=RCurl)

**Comment by umeshp7** [comment]
@nviraj Thank you for sharing this. This was helpful.
We have decided we'll add support for both. Because even ~370k downloads a month is a good number. 

We'll keep this thread up-to-date with the progress and also share sample snippets.

**Comment by mrworthington** [comment]
Just chiming in here that httr2 has been released. It is the successor to httr2. Not quite 300k a month, but having been released just over a year ago, ~35k/month is not insignificant. 

[![](https://cranlogs.r-pkg.org/badges/httr2)](https://cran.rstudio.com/web/packages/httr2/index.html)

**Comment by spechticus** [comment]
I am seconding the call for httr2 code snipper support! It is more state-of-the-R-art because it is pipe-able and provides really good support for oauth flows and caching!
