### ISSUE TITLE
Collection Level Headers Not Shown on Examples

### ISSUE THREAD

**Issue by rd67** [postmanlabs/postman-code-generators#367]
**Describe the bug**
If some headers like: Authorization are defined at collection level(Project Folder) then in the examples at right hand side these headers are missing.

**Expected code snippet and corresponding request**
These headers should be shown in all API's, it confuses a developer because the developer would expect the code to run when copied from example and tried on local device. Such as curl request etc.

**Comment by karmanya007** [comment]
@rd67 Could you tell me the steps to reproduce this problem.

**Comment by goodpaul6** [comment]
@karmanya007 Ran into this issue as well. Here are the steps:

1. I created an empty collection "Test"
2. I added a top-level request to this collection (no folders) with auth being inherited
3. I edited the "Test" collection Authorization to use Basic auth with username=test

This is what I saw on the generated docs:

![image](https://user-images.githubusercontent.com/3721423/97095511-42cd7580-162e-11eb-9e27-130446643972.png)

No authorization included in the curl request example despite it being inherited. When these docs were opened in postman, the resulting code was correct.

**Comment by rd67** [comment]
@karmanya007 Can you please provide any update on this issue?

**Comment by VShingala** [comment]
@rd67 @goodpaul6 Could you try this out with latest version of Postman App now? We've had few changes to how documentation is displayed. For example, here's [Stripe API documentation](https://www.postman.com/stripedev/workspace/stripe-developers/documentation/665823-2664f86d-f802-463a-b731-b68d6821464b) and going to particular request from this documentation, you can now see `Authorization` header in code snippet even though corresponding request doesn't have Auth defined.

Feel free to re-open this issue if you face any further problems.

![Image](https://github.com/postmanlabs/postman-code-generators/assets/16756296/2aad9e8e-209c-4adc-8dfd-fcedf5706145)
