### ISSUE TITLE
Let javascript-Fetch also have an option to generate async/await code.

### ISSUE THREAD

**Issue by user9747** [postmanlabs/postman-code-generators#390]
I use async/await fetch , so if i use the code generated from postman, I have to rewrite the request part. It would be way easier if postman is able to generate that as well. I think this applies to all the JS libs that postman generates code for.

**Comment by devangmukherjee** [comment]
Hi, I would like to work on this issue. Can someone please guide as to how should I proceed with this issue?

**Comment by user9747** [comment]
@webholik  Could i work on this if no one has picked it up?

**Comment by webholik** [comment]
@user9747 Adding async/wait is currently low priority for the project as not too may people have asked for it and from a usability point of view there is no gain from using it since the Promises work just fine. You are free to work on it but we might not be able to merge it in the near future.

**Comment by clairefro** [comment]
Bumping as we need this too
