### ISSUE TITLE
Issue with '{' and '}' on curl output - should be encoded

### ISSUE THREAD

**Issue by pfranck** [postmanlabs/postman-code-generators#415]
**Describe the bug**
The { and } are not encoded for curl output - causing curl to interpret differently the request
URL to reproduce: https://reqres.in/api/users?query={name, id}
curl version : 
```
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

**To Reproduce**
 - create a request with https://reqres.in/api/users (or any other endpoint)
 - add a parameter query with value `{name, id}`
 - go on code and copy the value of the curl request
 - execute the curl request with curl 7.68.0
 - the URL is not correctly interpreted and 2 request are trigger

**Expected code snippet and corresponding request**
If you have a working code snippet that you think solves your problem, please add it here:
```
curl --location --request GET 'https://reqres.in/api/users?query=%7Bname,%20id%7D' 
```
```
{
	"info": {
		"_postman_id": "620e6009-bd4a-4cfa-88aa-189bdf06547b",
		"name": "test",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "issue with { and }",
			"request": {
				"method": "GET",
				"header": [],
				"url": {
					"raw": "https://reqres.in/api/users?query={name, id}",
					"protocol": "https",
					"host": [
						"reqres",
						"in"
					],
					"path": [
						"api",
						"users"
					],
					"query": [
						{
							"key": "query",
							"value": "{name, id}"
						}
					]
				}
			},
			"response": []
		}
	],
	"protocolProfileBehavior": {}
}
```

**Additional context**
If you have any reference material which might help us debug the problem please add it here:
Version of postman-code-generators/Postman app: Postman v7.35.0

**Comment by webholik** [comment]
@pfranck Thanks for reporting the issue. Turns out we have already [fixed](https://github.com/postmanlabs/postman-code-generators/pull/258) this issue in this repo and it should be out in the next release of Postman app.
