### ISSUE TITLE
Add Support for C# HttpClient code gen

### ISSUE THREAD

**Issue by justindbaur** [postmanlabs/postman-code-generators#452]
**Is your feature request related to a problem? Please describe.**

I would love if Postman had the ability to generate code for making HTTP calls using the built in [`HttpClient`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-5.0) in `System.Net.Http`. Some companies have requirement to not use outside packages so using only things built into .NET could be helpful.  

**Describe the solution you'd like**

I would like it to generate code as close to the best practices as described by Microsoft and shown in this [example](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-5.0#examples).

**Additional context**

I am going to personally start working on this and will hopefully be referencing this issue in a pull request soon.

**Comment by Misiu** [comment]
@justindbaur any updates on this? This would be an awesome feature!

**Comment by justindbaur** [comment]
@Misiu Since you had shown some interest in it. I have just finished the implementation in #453. I was wondering if you could take a look at the samples and see if they look good to you. I want it to be a good introduction for people so I want it to be as close to how people would use it without getting to crazy.

**Comment by yuzd** [comment]
does it release now?

**Comment by justindbaur** [comment]
@yuzd It will need to be reviewed, approved, and merged by someone at postman. It doesn't look like a lot of resources are directed at this repo so it might take some time. I will do my best to be responsive to any issues with the pull request when a review comes my way though. Probably best to be subscribed to the linked PR.

**Comment by yuzd** [comment]
thanks ! this is great job for csharp

**Comment by jvitor83** [comment]
@umeshp7 we need this.
Can be merged and released?

**Comment by justindbaur** [comment]
Let me know how I can help @umeshp7

**Comment by markandrew21** [comment]
With the breaking changes introduced in RestSharp v107, and Postman not supporting RestSharp code generation for version 107 or higher, having HttpClient code generation in Postman would be a great addition to the software.
