### ISSUE TITLE
HTTP Code Generation does not handle x-www-form-urlencoded content correctly

### ISSUE THREAD

**Issue by DM-Francis** [postmanlabs/postman-code-generators#454]
**Describe the bug**
The raw request HTTP snippet does not correctly encode the request body when using the x-www-form-urlencoded content-type in the request builder.  It appears to encode some characters, but not all.  Note that the actual request has the correct content, but it is just the HTTP in the code snippet window.

**To Reproduce**

1. Create a request with a body type set to x-www-form-urlencoded.
2. Add a key-value pair with key `data` and value `example!£$%^&`
3. Inspect the raw HTTP code generated.  The body should be `data=example!%C2%A3%24%25%5E%26`, but is instead set to `data=example!£$%^%26`, it has only encoded the ampersand.

**Expected code snippet and corresponding request**
Expected HTTP code snippet:
```
POST / HTTP/1.1
Host: www.example.com
Content-Type: application/x-www-form-urlencoded
Content-Length: 33

data=example!%C2%A3%24%25%5E%26
```

**Screenshots**
Example request:
![image](https://user-images.githubusercontent.com/8194344/107667168-39bcee80-6c87-11eb-9da8-ab7821d16a10.png)

Incorrect HTTP code:
![image](https://user-images.githubusercontent.com/8194344/107667257-522d0900-6c87-11eb-86a7-82aa89e59094.png)

**Comment by webholik** [comment]
@DM-Francis That's for your work! It may take a couple weeks for the fix to make it to the Postman app.
