### ISSUE TITLE
Add Support for Kotlin OkHttp code gen

### ISSUE THREAD

**Issue by nilsjr** [postmanlabs/postman-code-generators#491]
**Is your feature request related to a problem? Please describe.**

Due the increased usage of Kotlin in the Android & JVM world, I would like to see more Kotlin code generators. As the language evolves rapidly over last years it should be part of Postman.

More than the half of all Android projects in the world already use Kotlin as their primary programming language:
[Kotlin ecosystem report 2020](https://www.jetbrains.com/lp/devecosystem-2020/kotlin/)

The superior network library OkHttp from Square is also rewritten in Kotlin:
[OkHttp 4.x](https://square.github.io/okhttp/upgrading_to_okhttp_4/)

**Describe the solution you'd like**

Similar to **java-okhttp** code generator only in Kotlin. 😄 

**Additional context**

We at [NanoGiants](https://github.com/nanogiants) use OkHttp for all of our Android projects, so I hope we can get this code gen in a future postman release.

**Comment by nilsjr** [comment]
@webholik I opened a PR 10 months ago. Is it possible to get feedback for that?

**Comment by webholik** [comment]
@nilsjr Sorry for the delay but as the number of codegens in the repository has gotten very large, we've decided to limit the addition of new codegens unless we get a lot of user requests for it. We're still evaluating the demand for Kotlin-Okhttp. I'll update you as soon as we reach a decision.
