### ISSUE TITLE
Golang Replace ioutil.ReadAll with io.ReadAll

### ISSUE THREAD

**Issue by Prajwal-Koirala** [postmanlabs/postman-code-generators#496]
Hello,
`ioutil.ReadAll` has been deprecated and been replaced with `io.ReadAll`

https://golang.org/pkg/io/ioutil/#ReadAll

**Comment by webholik** [comment]
@Prajwal-Koirala `io.ReadAll` was introduced in Go v1.16. Since we also support versions prior to that, we'll keep this in code for the time being.

**Comment by Avinash7390** [comment]
Hey, ioutil.ReadAll reads the whole content and there might be the problem of memory leak, does io.ReadAll do the same?
