### ISSUE TITLE
Failing url encoding in multiple codegens due to back call to Url.getQueryString

### ISSUE THREAD

**Issue by jpoehnelt** [postmanlabs/postman-code-generators#506]
`Url.getQueryString({encode: true})` is no longer supported (https://github.com/postmanlabs/postman-collection/pull/1198/files#diff-0267b663041b4094bb4802be9641a818f458a54127910a9126e61ae9d499232eL313). 

This leads to urls that are not properly encoded in the following codegens:

- curl
- swift
- java-unirest

https://github.com/postmanlabs/postman-code-generators/search?q=getQueryString

**Comment by jpoehnelt** [comment]
It seems many other codegens use the `request.url.toString()` pattern.

**Comment by jpoehnelt** [comment]
seems to be mostly a local issue where i had postman-collection@4.0. downgrading to 3.x fixed the issue for now. this still needs to be updated though.

**Comment by saksham-postman** [comment]
@jpoehnelt , the issue was fixed with this [PR](https://github.com/postmanlabs/postman-code-generators/pull/638)
