### ISSUE TITLE
Go: Wrong code generation if body contains an empty string in string array

### ISSUE THREAD

**Issue by akshaybharambe14** [postmanlabs/postman-code-generators#510]
**Describe the bug**
Wrong Go code is generated if the request body of type array of string contains an empty string. ex. ["b", "", "a"]

**To Reproduce**
Use following request body and generate go code
```json
[
    "b",
    "",
    "a"
]
```
**Expected code snippet and corresponding request**
Request - 
```sh
curl --location --request POST 'https://example.com/users/roles' \
--header 'Content-Type: application/json' \
--data-raw '[
    "b",
    "",
    "a"
]'
```
Generated code - https://play.golang.org/p/kJuPMKHIm__y

```go
  payload := strings.NewReader(`[`+"
"+`
    "b",`+"
"+`
    "",`+"
"+`
    "a"`+"
"+`
]`)
```

Expected code - https://play.golang.org/p/q35o4Ll4NMV

```go
payload := strings.NewReader(`[
    "b",
    "",
    "a"
]`)
```

**Screenshots**
N/A

**Additional context**
I feel, additional spaces are causing problems. If we can omit the space and use raw body, this problem can be fixed.

Version of postman-code-generators/Postman app: Postman v8.8.0

**Comment by webholik** [comment]
@akshaybharambe14 This issue seems to have been fixed in the latest version of Postman (v10.13). Can you confirm?
<img width="1004" alt="Screenshot 2023-04-26 at 3 21 53 PM" src="https://user-images.githubusercontent.com/360759/234539767-ed332067-dcee-48e9-bc1e-c829ef90ca5b.png">

**Comment by akshaybharambe14** [comment]
Strange, I am using Version 10.13.6 and it is still producing the same result.

<img width="752" alt="image" src="https://github.com/postmanlabs/postman-code-generators/assets/20267156/de8caeef-e460-47ed-a0d6-90244c522722">

<img width="757" alt="image" src="https://github.com/postmanlabs/postman-code-generators/assets/20267156/fd4e0108-72e1-4634-8334-2d6ca3ad3ec4">

**Comment by VShingala** [comment]
@akshaybharambe14 This has been fixed with latest Postman App. Feel free to reopen this issue if you face any further problem with it.
