### ISSUE TITLE
Not responding

### ISSUE THREAD

**Issue by abhiPHPDev** [postmanlabs/postman-code-generators#514]
**Describe the bug**
After entered correct Credentials with post method Its getting response code error
**To Reproduce**
for login: I Entered all the required fields but its not working properly

**Expected code snippet and corresponding request**
If you have a working code snippet that you think solves your problem, please add it here:
Also, add the request.json for which this code snippet was generated.

**Screenshots**
![image](https://user-images.githubusercontent.com/11054811/127870142-8de1a48d-cc0e-4200-a0c5-fcd50fd6d87d.png)

Please do the needful

**Comment by webholik** [comment]
Closing as not related to Code Generators

**Comment by umeshp7** [comment]
@abhiPHPDev You can raise this issue on the github.com/postmanlabs/postman-app-support repo to get more help. 

Also for the above, can you check the URL again? The error comes usually when the URL is malformed and doesn't seem to be a Postman issue.
