### ISSUE TITLE
Add Support for 1C/OneScript Connector/1connector code gen

### ISSUE THREAD

**Issue by malikov-pro** [postmanlabs/postman-code-generators#546]
**Is your feature request related to a problem? Please describe.**
1C:Enterprise is a universal cloud and on-premise system of programs for automating a company’s financial and wider operational activities. https://1c-dn.com/
OneScript an independent cross-platform implementation of a virtual machine that executes scripts in the language 1C:Enterprise

**Describe the solution you'd like**
Code generation uses Connector/1connector.

**Additional context**
1C has an HTTP client, there is also a library for working with HTTP requests, an analogue of Requests for Python.

For 1C:  https://github.com/vbondarevsky/Connector
For OneScript: https://github.com/vbondarevsky/1connector

Most 1C programmers use Russian, but the platform also supports English. The Connector library has been translated into English.

For testing, it is better to use OneScript because it runs without checking the license and is also supported by GitHub Actions. https://github.com/marketplace/actions/setup-onescript-action

**Comment by DeathError** [comment]
Good afternoon. When will it be officially added? but for now everyone is using the fork https://github.com/malikov-pro/postman-code-generators/tree/develop/codegens/onescript-1connector

**Comment by johnnyshut** [comment]
is there any hope of adding support?
