### ISSUE TITLE
Joomla 4 API Docs update?

### ISSUE THREAD

**Issue by tonypartridge** [postmanlabs/postman-code-generators#575]
Where can we update the Joomla 4 API Docs? The routes for article needs changing to articles.

**Comment by webholik** [comment]
Hey @tonypartridge, can you better describe your question and how it is related to postman-code-generators?

**Comment by stell** [comment]
@webholik This endpoint 
https://documenter.getpostman.com/view/9617873/Szzj9yJy#7cb4b1ab-4203-41bf-b6c8-ae9ffb94ffe0
should be changed to 
`joomla4.local/api/index.php/v1/content/articles`

**Comment by dhwaneetbhatt** [comment]
Hello @tonypartridge, this API is hosted on our public network: https://www.postman.com/JoomlaLABS/workspace/luca-racchetti-s-public-workspace/documentation/9617873-2e24206f-872e-402d-85f0-f5831b8afd43. It is not maintained by Postman. It would be great if you could contact the author and suggest any updates.

You could also fork and submit a PR to the original collection to ease this process. You can press the **Run in Postman** button in your shared documentation link, fork the collection in your workspace, and submit changes to the original collection.

Helpful articles:
- [Forking Postman entities](https://learning.postman.com/docs/collaborating-in-postman/using-version-control/forking-entities/)
- [Creating pull requests](https://learning.postman.com/docs/collaborating-in-postman/using-version-control/creating-pull-requests/)
