### ISSUE TITLE
Request to remove html from the pet description

### ISSUE THREAD

**Issue by kirsty14** [postmanlabs/postman-code-generators#584]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the api retrieves html inside the description and I am frustrated when the description is in a different language. 

Example: <br><br>Baba est un tr&#65533;s jeune m&#65533;le tout en finesse,

**Describe the solution you'd like**
If possible could you please remove the html tags from the description as it is a nightmare to do string manipulation on the inconsistent html tags inside the description. Could you please only make the API return JSON only in English.

**Additional context**
Awesome API. I am really enjoying it. Keep up the good work!

**Comment by webholik** [comment]
Hey @kirsty14 , can you better describe your question and how it is related to postman-code-generators? Which API are you talking about?

**Comment by kirsty14** [comment]
Good afternoon,

I am not sure if you can help me resolve this.

Inside the ADOPTAPET API there is html that Is included in the pet description as well as a foreign language that I would really like removed from the API if possible.

**Comment by webholik** [comment]
Hey @kirsty14 I'm sorry but we cannot help you with this. You need to contact adoptapet.com to make the changes in their API that you want.
