### ISSUE TITLE
Upgrade Postman-code-generators dependencies to new versions to fix security vulnerabilities

### ISSUE THREAD

**Issue by Mayankyadav123** [postmanlabs/postman-code-generators#586]
**Is your feature request related to a problem? Please describe.**
When we do npm audit we are getting security warning for shelljs causing issues with security clearance from our devops teams.

**Describe the solution you'd like**
We need to upgrade shelljs version in package.json to 0.8.5 i.e latest to get the security vulnerability fix.

**Additional context**

**Comment by webholik** [comment]
Close this as all dependencies have been upgraded.
