### ISSUE TITLE
PaymOE

### ISSUE THREAD

**Issue by Swhistler1** [postmanlabs/postman-code-generators#650]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by Swhistler1** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.

****

**Comment by dhwaneetbhatt** [comment]
@Swhistler1 Could you please add the relevant details? The issue description does not contain anything.
