### ISSUE TITLE
content is not correct encode

### ISSUE THREAD

**Issue by siqiniao** [postmanlabs/postman-code-generators#86]
![image](https://user-images.githubusercontent.com/2796825/64164654-298bc780-ce76-11e9-8f30-8ff4a7a57799.png)
![image](https://user-images.githubusercontent.com/2796825/64164675-33152f80-ce76-11e9-84ea-5165d7b95d9a.png)

content should be urlencoded，but now is %uxxx， so my api get request params is like
{"content":"%u4E2D%u56FD"}

**not the original string**

**Comment by abhijitkane** [comment]
@siqiniao Starting Postman 7.7.2, we've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet with the 'New Code Generation Mode' flag enabled in Postman's global settings.

This particular problem has been solved as well.

Hope this addresses your concerns.
